server:
  port: 8700
eureka:
  client:
    service-url:
      defaultZone: http://172.16.134.98:8761/eureka/
  instance:
    instance-id: gateway-module-app
spring:
  application:
    name: gateway-module
  main:
      allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          #匹配所有路径
          '[/**]':
            allowedOrigins: "http://172.16.90.68:7777"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTIONS
      #路由配置
      routes:
        - id: evalRoute
          uri: "http://172.16.134.98:8762"
          predicates:
          - Path=/eval/**
        - id: targetRoute
          uri: "http://172.16.134.98:8763"
          predicates:
          - Path=/target/**
        - id: salaryRoute
          uri: "http://172.16.134.98:8764"
          predicates:
          - Path=/salary/**
        - id: authRoute
          uri: "http://172.16.134.98:8765"
          predicates:
          - Path=/auth/**
info:
  app.name: gateway-module-app
  company.name: yuchai
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$








