server:
  port: 8761
eureka:
  instance:
    hostname: 172.16.134.98
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://${eureka.instance.hostname}:8760/eureka/
spring:
  application:
    name: eureka-service-module