server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
    #eureka 高可用集群配置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka,http://eureka1:8760/eureka
spring:
  application:
    name: eureka-service-module